spring:
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://localhost:5432/demo_test
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

app:
  home:
    products-per-page: 10
    number-of-best-selling-products: 5
